# below settings to
# - generate the html pages only
auto: false
server: false

# below settings to
# - generate the html pages
# - start a http server on http://localhost:4000
# - regenerate automatically after source file changes
# auto: true
# server: true
# server_port: 4000
